# -*- coding: utf-8 -*-
"""weatherbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zjOgd0vPMpsKH7jyi50jF7cQDrSzQEf7
"""

import requests

# Weatherbit API endpoint and API key
API_ENDPOINT = "https://api.weatherbit.io/v2.0/current"
API_KEY = "179784eb079047b780b3334225d958bc"

def get_weather(location):
    # Make a GET request to the Weatherbit API
    params = {
        "city": location,
        "key": API_KEY,
        "units": "M"
    }
    response = requests.get(API_ENDPOINT, params=params)

    # Check if the request was successful
    if response.status_code == 200:
        weather_data = response.json()
        return weather_data
    else:
        return None

def parse_weather_data(weather_data):
    # Extract relevant weather information from the API response
    # Adjust the parsing logic based on the Weatherbit API response structure
    temperature = weather_data["data"][0]["temp"]
    humidity = weather_data["data"][0]["rh"]
    wind_speed = weather_data["data"][0]["wind_spd"]
    weather_conditions = weather_data["data"][0]["weather"]["description"]
    rain = "rain" in weather_data["data"][0]

    return temperature, humidity, wind_speed, weather_conditions, rain

def format_weather_response(location, temperature, humidity, wind_speed, weather_conditions, rain):
    # Format the weather information into a user-friendly response
    response = f"Weather information for {location}:"
    response += f"\nTemperature: {temperature}°C"
    response += f"\nHumidity: {humidity}%"
    response += f"\nWind Speed: {wind_speed} m/s"
    response += f"\nWeather Conditions: {weather_conditions}"

    if rain:
        response += "\nIt will rain today."
    else:
        response += "\nNo rain is expected today."

    return response

def chatbot():
    print("Welcome to the Weather Information Chatbot!")
    print("You can ask for the weather by typing a location.")
    print("To exit, simply type 'exit'.\n")

    while True:
        user_input = input("Please enter a location: ")

        if user_input.lower() == "exit":
            print("Goodbye!")
            break

        weather_data = get_weather(user_input)

        if weather_data is not None and "data" in weather_data and len(weather_data["data"]) > 0:
            temperature, humidity, wind_speed, weather_conditions, rain = parse_weather_data(weather_data)

            response = format_weather_response(user_input, temperature, humidity, wind_speed, weather_conditions, rain)
            print(response)
        else:
            print("Sorry, weather information for that location is unavailable. Please try again.\n")

# Start the chatbot
chatbot()